import Provider from '@/provider'
import { ToastContainer } from 'react-toastify'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <Provider>
        <html className="!scroll-smooth">
          <body className="overflow-x-hidden">
            <ToastContainer style={{ top: '120px' }} />
            {children}
          </body>
        </html>
      </Provider>
    </>
  )
}
